// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"MWG_SkipTitle","status":true,"description":"Skips title or auto-loads Save 0 (auto-save) and triggers a Common Event.","parameters":{"CommonEventID":"0"}},
{"name":"EliMZ_Book","status":true,"description":"♦6.1.0♦ Essential plugin for all Eli plugins.","parameters":{"checkVersion":"false","updateErrorPrinter":"false","iterateEventList":"true","engine":"{\"styleOverflow\":\"false\",\"disableEffekseer\":\"false\",\"--- BUG FIXES ---\":\"\",\"fixBitmapStartLoad\":\"true\"}","playtest":"{\"gameFocus\":\"false\",\"enableGameWindowPosition\":\"false\",\"alignX\":\"left\",\"offsetX\":\"10\",\"alignY\":\"center\",\"offsetY\":\"10\",\"openDevTools\":\"false\",\"quickRestart\":\"true\",\"startFps\":\"false\"}"}},
{"name":"EliMZ_EasingPicture","status":true,"description":"♦1.2.4♦ Add more easing animations to pictures!","parameters":{}},
{"name":"SRD_MagicVariableUtil","status":true,"description":"Adds a JavaScript utility object that makes working with variables and switches in code much easier and readable.","parameters":{"Automatically Create Helper":"true","Utility Variable Name":"v","Utility Switch Name":"s"}},
{"name":"MWG_AlwaysActive","status":true,"description":"Prevents the game from pausing when the window loses focus.","parameters":{}},
{"name":"MWG_AnchorHijack","status":true,"description":"[v1.0] Hijacks standard Picture Origins to allow for \"Bottom-Center\" anchoring.","parameters":{"targetOrigin":"0"}},
{"name":"SRD_UltraBase","status":true,"description":"Contains code required for HUD Maker Ultra. Does not affect the RPG Maker codebase.","parameters":{}},
{"name":"SRD_HUDMakerUltra","status":true,"description":"Allows you to create and use HUDs for the map and battles.\r\nRequires the HUD Maker Ultra editor.","parameters":{"Auto-Reload HUD Data":"false","Enable Screenshots":"false","Hide Battle Status Window":"false","Hide Battle Selection Window":"false","Fade During Events":"true","Event Fade Opacity":"255","Fade Duration":"10","Map Visibility Code":"return true;","Battle Visibility Code":"return true;"}},
{"name":"SRD_HUDMakerUltraPro","status":true,"description":"The pro version of HUD Maker Ultra. It works like an extension plugin, so please make sure SRD_HUDMakerUltra is still installed before this.","parameters":{}},
{"name":"SRD_HUDMakerUltraMultiline","status":true,"description":"This plugin allows \\n to be used in code strings to make new-lines in text component.\r\nRequires the HUD Maker Ultra editor.","parameters":{}},
{"name":"SRD_HighAFPicturesMZ","status":true,"description":"","parameters":{}}
];
