// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"MWG_SkipTitle","status":true,"description":"Skips title or auto-loads Save 0 (auto-save) and triggers a Common Event.","parameters":{"CommonEventID":"0"}}
];
